// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/token/v1 (interfaces: TokenServiceClient)
//
// Generated by this command:
//
//	mockgen -package v1 ./api/token/v1 TokenServiceClient
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	token "github.com/amimof/multikube/api/token/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockTokenServiceClient is a mock of TokenServiceClient interface.
type MockTokenServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceClientMockRecorder
	isgomock struct{}
}

// MockTokenServiceClientMockRecorder is the mock recorder for MockTokenServiceClient.
type MockTokenServiceClientMockRecorder struct {
	mock *MockTokenServiceClient
}

// NewMockTokenServiceClient creates a new mock instance.
func NewMockTokenServiceClient(ctrl *gomock.Controller) *MockTokenServiceClient {
	mock := &MockTokenServiceClient{ctrl: ctrl}
	mock.recorder = &MockTokenServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenServiceClient) EXPECT() *MockTokenServiceClientMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockTokenServiceClient) Issue(ctx context.Context, in *token.IssueRequest, opts ...grpc.CallOption) (*token.IssueResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Issue", varargs...)
	ret0, _ := ret[0].(*token.IssueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockTokenServiceClientMockRecorder) Issue(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockTokenServiceClient)(nil).Issue), varargs...)
}

// Revoke mocks base method.
func (m *MockTokenServiceClient) Revoke(ctx context.Context, in *token.RevokeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Revoke", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenServiceClientMockRecorder) Revoke(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenServiceClient)(nil).Revoke), varargs...)
}
