
image: golang:1.12

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#   - /go/src

# before_script: 
#   - export GOPATH=/go/
#   - mkdir -p $GOPATH

stages:
  - test
  - build

test:
  stage: test
  script:
    - make fmt  
    - make vet 
    - make gocyclo
    - make golint 
    - make ineffassign
    - make misspell
    - make test

compile:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin/multikube-linux-amd64
      - bin/multikube-linux-arm
      - bin/multikube-darwin-amd64
      - bin/multikube-windows-amd64.exe
