sudo: false
dist: xenial
language: go

go:
  - "1.13"
  
stages:
- test
- build
- deploy

jobs:
  include:
  - stage: test
    name: "Verify"
    script: 
    - make checkfmt
    - make fmt  
    - make vet 
    - make race
    - make gocyclo
    - make golint 
    - make ineffassign
    - make misspell

  - name: "Unit Test"
    script:
    - make test
    - make benchmark
    - make coverage

  - name: "Compile"
    stage: build
    script: 
    - make

  - stage: deploy
    name: "GitHub Releases"
    script:
    - GOOS=linux GOARCH=amd64 BUILDPATH=./bin/multikube-linux-amd64 make
    - GOOS=linux GOARCH=arm BUILDPATH=./bin/multikube-linux-arm make
    - GOOS=linux GOARCH=arm64 BUILDPATH=./bin/multikube-linux-arm64 make
    - GOOS=windows GOARCH=amd64 BUILDPATH=./bin/multikube-windows-amd64.exe make
    - GOOS=darwin GOARCH=amd64 BUILDPATH=./bin/multikube-darwin-amd64 make
    deploy:
      provider: releases
      api_key: ${GITHUB_API_KEY}
      file:
      - bin/multikube-linux-amd64
      - bin/multikube-linux-arm
      - bin/multikube-linux-arm64
      - bin/multikube-windows-amd64.exe
      - bin/multikube-darwin-amd64
      skip_cleanup: true
      draft: true
      on:
        tags: true