swagger: "2.0"
info:
  description: Manages multiple Kubernetes clusters and provides a single API to clients
  title: Kubernetes multi-cluster manager
  version: 1.0.0
consumes:
- application/io.multikube.v1+json
produces:
- application/io.multikube.v1+json
schemes:
- http
- https
definitions:
  cluster:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string 
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /clusters:
    get:
      tags:
        - clusters
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
      responses:
        200:
          description: List the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/cluster"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - clusters
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/cluster"
      responses:
        201:
          description: Cluster created
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /clusters/{id}:
    parameters:
      - name: id
        type: string
        in: path
        required: true
    get:
      tags:
        - clusters
      operationId: getOne
      responses:
        200:
          description: Got cluster
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - clusters
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/cluster"
      responses:
        200:
          description: Updated cluster
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - clusters
      operationId: destroyOne
      responses:
        204:
          description: Cluster deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
