swagger: "2.0"
consumes:
- application/io.multikube.v1+json
produces:
- application/io.multikube.v1+json
schemes:
- http
info:
  description: Multi Kubernetes cluster management
  title: Multi Kubernetes cluster manager
  version: 1.0.0
definitions:
  cluster:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /:
    get:
      tags:
        - clusters
      parameters:
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: Get clusters
          schema:
            type: array
            items:
              $ref: "#/definitions/cluster"
        default:
          description: Genering error response
          schema:
            $ref: "#/definitions/error"
