swagger: "2.0"
consumes:
- application/io.multikube.v1+json
produces:
- application/io.multikube.v1+json
schemes:
- http
info:
  description: Multi Kubernetes cluster management
  title: Multi Kubernetes cluster manager
  version: 1.0.0
definitions:
  cluster:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /:
    get:
      tags:
        - clusters
      operationId: findMany
      parameters:
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: Get clusters
          schema:
            type: array
            items:
              $ref: "#/definitions/cluster"
        default:
          description: Genering error response
          schema:
            $ref: "#/definitions/error"
  /:
    post:
      tags:
        - clusters
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/cluster"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags: 
        - clusters
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/cluster"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - clusters
      operationId: deleteOne
      parameters:
        - type: integer
          format: int64
          name: id
          in: path
          required: true
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

