// Code generated by go-swagger; DO NOT EDIT.

/*
Package server Kubernetes multi-cluster manager
Manages multiple Kubernetes clusters and provides a single API to clients


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/io.multikube.v1+json

    Produces:
    - application/io.multikube.v1+json

swagger:meta
*/
package server
