// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/credential/v1 (interfaces: CredentialServiceClient)
//
// Generated by this command:
//
//	mockgen -package v1 ./api/credential/v1 CredentialServiceClient
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	credential "github.com/amimof/multikube/api/credential/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCredentialServiceClient is a mock of CredentialServiceClient interface.
type MockCredentialServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialServiceClientMockRecorder
	isgomock struct{}
}

// MockCredentialServiceClientMockRecorder is the mock recorder for MockCredentialServiceClient.
type MockCredentialServiceClientMockRecorder struct {
	mock *MockCredentialServiceClient
}

// NewMockCredentialServiceClient creates a new mock instance.
func NewMockCredentialServiceClient(ctrl *gomock.Controller) *MockCredentialServiceClient {
	mock := &MockCredentialServiceClient{ctrl: ctrl}
	mock.recorder = &MockCredentialServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialServiceClient) EXPECT() *MockCredentialServiceClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredentialServiceClient) Create(ctx context.Context, in *credential.CreateRequest, opts ...grpc.CallOption) (*credential.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*credential.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCredentialServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredentialServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockCredentialServiceClient) Delete(ctx context.Context, in *credential.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCredentialServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCredentialServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockCredentialServiceClient) Get(ctx context.Context, in *credential.GetRequest, opts ...grpc.CallOption) (*credential.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*credential.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCredentialServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCredentialServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockCredentialServiceClient) List(ctx context.Context, in *credential.ListRequest, opts ...grpc.CallOption) (*credential.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*credential.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCredentialServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCredentialServiceClient)(nil).List), varargs...)
}

// Patch mocks base method.
func (m *MockCredentialServiceClient) Patch(ctx context.Context, in *credential.PatchRequest, opts ...grpc.CallOption) (*credential.PatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*credential.PatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockCredentialServiceClientMockRecorder) Patch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCredentialServiceClient)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockCredentialServiceClient) Update(ctx context.Context, in *credential.UpdateRequest, opts ...grpc.CallOption) (*credential.UpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*credential.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCredentialServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCredentialServiceClient)(nil).Update), varargs...)
}
