// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: audit/v1/audit.proto

package audit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	AuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (AuditService_AuditLogClient, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) AuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (AuditService_AuditLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuditService_ServiceDesc.Streams[0], "/audit.v1.AuditService/AuditLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &auditServiceAuditLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuditService_AuditLogClient interface {
	Recv() (*AuditLogResponse, error)
	grpc.ClientStream
}

type auditServiceAuditLogClient struct {
	grpc.ClientStream
}

func (x *auditServiceAuditLogClient) Recv() (*AuditLogResponse, error) {
	m := new(AuditLogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility
type AuditServiceServer interface {
	AuditLog(*AuditLogRequest, AuditService_AuditLogServer) error
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuditServiceServer struct {
}

func (UnimplementedAuditServiceServer) AuditLog(*AuditLogRequest, AuditService_AuditLogServer) error {
	return status.Errorf(codes.Unimplemented, "method AuditLog not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_AuditLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuditLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditServiceServer).AuditLog(m, &auditServiceAuditLogServer{stream})
}

type AuditService_AuditLogServer interface {
	Send(*AuditLogResponse) error
	grpc.ServerStream
}

type auditServiceAuditLogServer struct {
	grpc.ServerStream
}

func (x *auditServiceAuditLogServer) Send(m *AuditLogResponse) error {
	return x.ServerStream.SendMsg(m)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuditLog",
			Handler:       _AuditService_AuditLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "audit/v1/audit.proto",
}
