// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/policy/v1 (interfaces: PolicyServiceClient)
//
// Generated by this command:
//
//	mockgen -package v1 ./api/policy/v1 PolicyServiceClient
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	policy "github.com/amimof/multikube/api/policy/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockPolicyServiceClient is a mock of PolicyServiceClient interface.
type MockPolicyServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyServiceClientMockRecorder
	isgomock struct{}
}

// MockPolicyServiceClientMockRecorder is the mock recorder for MockPolicyServiceClient.
type MockPolicyServiceClientMockRecorder struct {
	mock *MockPolicyServiceClient
}

// NewMockPolicyServiceClient creates a new mock instance.
func NewMockPolicyServiceClient(ctrl *gomock.Controller) *MockPolicyServiceClient {
	mock := &MockPolicyServiceClient{ctrl: ctrl}
	mock.recorder = &MockPolicyServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyServiceClient) EXPECT() *MockPolicyServiceClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPolicyServiceClient) Create(ctx context.Context, in *policy.CreateRequest, opts ...grpc.CallOption) (*policy.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*policy.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPolicyServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPolicyServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockPolicyServiceClient) Delete(ctx context.Context, in *policy.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPolicyServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPolicyServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockPolicyServiceClient) Get(ctx context.Context, in *policy.GetRequest, opts ...grpc.CallOption) (*policy.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*policy.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPolicyServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPolicyServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockPolicyServiceClient) List(ctx context.Context, in *policy.ListRequest, opts ...grpc.CallOption) (*policy.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*policy.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPolicyServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPolicyServiceClient)(nil).List), varargs...)
}

// Patch mocks base method.
func (m *MockPolicyServiceClient) Patch(ctx context.Context, in *policy.PatchRequest, opts ...grpc.CallOption) (*policy.PatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*policy.PatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockPolicyServiceClientMockRecorder) Patch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockPolicyServiceClient)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockPolicyServiceClient) Update(ctx context.Context, in *policy.UpdateRequest, opts ...grpc.CallOption) (*policy.UpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*policy.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPolicyServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPolicyServiceClient)(nil).Update), varargs...)
}
