syntax = "proto3";

package token.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "meta/v1/meta.proto";

option go_package = "github.com/amimof/multikube/api/token/v1;token";

service TokenService {
  rpc Issue(IssueRequest) returns (IssueResponse) {
    option (google.api.http) = {
      post: "/api/v1/tokens"
      body: "token"
    };
  }
  rpc Revoke(RevokeRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/tokens/{uid}"
      additional_bindings: {delete: "/api/v1/tokens/{name}"}
    };
  }
}

message Token {
  TokenConfig config = 3;
}

message TokenStatus {}

message TokenConfig {
  string subject = 1;
  string username = 2;
  repeated string groups = 3;
  repeated string roles = 4;
  string audience = 5;
  repeated string scopes = 6;
  repeated string clusters = 7;
  repeated string service_accounts = 8;
  optional uint64 ttl = 9;
  map<string, string> extra_claims = 10;
}

message IssueRequest {
  Token token = 1 [(buf.validate.field).required = true];
}

message IssueResponse {
  // AccessToken string
  // ExpiresAt   time.Time
  // KeyID       string
  // TokenType   string
  string access_token = 1;
  google.protobuf.Timestamp expires_at = 2;
  string key_id = 3;
  string token_type = 4;
}

message RevokeRequest {
  option (buf.validate.message).oneof = {
    fields: [
      "uid",
      "name"
    ]
  };
  string uid = 1 [(buf.validate.field).string.min_len = 1];
  string name = 2 [(buf.validate.field).string.min_len = 1];
  bool purge = 3;
}
