---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multikube
  labels:
    app: multikube
---
apiVersion: v1
kind: Service
metadata:
  name: multikube
  labels:
    app: multikube
spec:
  ports:
    - name: grpc-5743
      port: 5743
      protocol: TCP
      targetPort: grpc
    - name: https-8443
      port: 8443
      protocol: TCP
      targetPort: https
    - name: metrics
      port: 8888
      protocol: TCP
      targetPort: metrics
  selector:
    app: multikube
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multikube
  labels:
    app: multikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multikube
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multikube
      annotations:
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
    spec:
      volumes:
        - name: multikube-data
          emptyDir: {}
      containers:
        - name: multikube
          image: "ghcr.io/amimof/multikube:latest"
          ports:
            - name: grpc
              containerPort: 5743
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          imagePullPolicy: Always
          volumeMounts:
            - name: multikube-data
              mountPath: "/.local/state/multikube"
      serviceAccount: multikube
      serviceAccountName: multikube
