// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/backend/v1 (interfaces: BackendServiceClient)
//
// Generated by this command:
//
//	mockgen -package v1 ./api/backend/v1 BackendServiceClient
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	backend "github.com/amimof/multikube/api/backend/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockBackendServiceClient is a mock of BackendServiceClient interface.
type MockBackendServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBackendServiceClientMockRecorder
	isgomock struct{}
}

// MockBackendServiceClientMockRecorder is the mock recorder for MockBackendServiceClient.
type MockBackendServiceClientMockRecorder struct {
	mock *MockBackendServiceClient
}

// NewMockBackendServiceClient creates a new mock instance.
func NewMockBackendServiceClient(ctrl *gomock.Controller) *MockBackendServiceClient {
	mock := &MockBackendServiceClient{ctrl: ctrl}
	mock.recorder = &MockBackendServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendServiceClient) EXPECT() *MockBackendServiceClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBackendServiceClient) Create(ctx context.Context, in *backend.CreateRequest, opts ...grpc.CallOption) (*backend.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*backend.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBackendServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBackendServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockBackendServiceClient) Delete(ctx context.Context, in *backend.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockBackendServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackendServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockBackendServiceClient) Get(ctx context.Context, in *backend.GetRequest, opts ...grpc.CallOption) (*backend.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*backend.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBackendServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBackendServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockBackendServiceClient) List(ctx context.Context, in *backend.ListRequest, opts ...grpc.CallOption) (*backend.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*backend.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBackendServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBackendServiceClient)(nil).List), varargs...)
}

// Patch mocks base method.
func (m *MockBackendServiceClient) Patch(ctx context.Context, in *backend.PatchRequest, opts ...grpc.CallOption) (*backend.PatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*backend.PatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockBackendServiceClientMockRecorder) Patch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockBackendServiceClient)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockBackendServiceClient) Update(ctx context.Context, in *backend.UpdateRequest, opts ...grpc.CallOption) (*backend.UpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*backend.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBackendServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBackendServiceClient)(nil).Update), varargs...)
}

// UpdateStatus mocks base method.
func (m *MockBackendServiceClient) UpdateStatus(ctx context.Context, in *backend.UpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStatus", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBackendServiceClientMockRecorder) UpdateStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBackendServiceClient)(nil).UpdateStatus), varargs...)
}
