// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/certificate/v1 (interfaces: CertificateServiceClient)
//
// Generated by this command:
//
//	mockgen -package v1 ./api/certificate/v1 CertificateServiceClient
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	certificate "github.com/amimof/multikube/api/certificate/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCertificateServiceClient is a mock of CertificateServiceClient interface.
type MockCertificateServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateServiceClientMockRecorder
	isgomock struct{}
}

// MockCertificateServiceClientMockRecorder is the mock recorder for MockCertificateServiceClient.
type MockCertificateServiceClientMockRecorder struct {
	mock *MockCertificateServiceClient
}

// NewMockCertificateServiceClient creates a new mock instance.
func NewMockCertificateServiceClient(ctrl *gomock.Controller) *MockCertificateServiceClient {
	mock := &MockCertificateServiceClient{ctrl: ctrl}
	mock.recorder = &MockCertificateServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateServiceClient) EXPECT() *MockCertificateServiceClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCertificateServiceClient) Create(ctx context.Context, in *certificate.CreateRequest, opts ...grpc.CallOption) (*certificate.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*certificate.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCertificateServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCertificateServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockCertificateServiceClient) Delete(ctx context.Context, in *certificate.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCertificateServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCertificateServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockCertificateServiceClient) Get(ctx context.Context, in *certificate.GetRequest, opts ...grpc.CallOption) (*certificate.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*certificate.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCertificateServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCertificateServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockCertificateServiceClient) List(ctx context.Context, in *certificate.ListRequest, opts ...grpc.CallOption) (*certificate.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*certificate.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCertificateServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCertificateServiceClient)(nil).List), varargs...)
}

// Patch mocks base method.
func (m *MockCertificateServiceClient) Patch(ctx context.Context, in *certificate.PatchRequest, opts ...grpc.CallOption) (*certificate.PatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*certificate.PatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockCertificateServiceClientMockRecorder) Patch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCertificateServiceClient)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockCertificateServiceClient) Update(ctx context.Context, in *certificate.UpdateRequest, opts ...grpc.CallOption) (*certificate.UpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*certificate.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCertificateServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCertificateServiceClient)(nil).Update), varargs...)
}
