// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/ca/v1 (interfaces: CertificateAuthorityServiceClient)
//
// Generated by this command:
//
//	mockgen -package v1 ./api/ca/v1 CertificateAuthorityServiceClient
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	certificate_authority "github.com/amimof/multikube/api/ca/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCertificateAuthorityServiceClient is a mock of CertificateAuthorityServiceClient interface.
type MockCertificateAuthorityServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateAuthorityServiceClientMockRecorder
	isgomock struct{}
}

// MockCertificateAuthorityServiceClientMockRecorder is the mock recorder for MockCertificateAuthorityServiceClient.
type MockCertificateAuthorityServiceClientMockRecorder struct {
	mock *MockCertificateAuthorityServiceClient
}

// NewMockCertificateAuthorityServiceClient creates a new mock instance.
func NewMockCertificateAuthorityServiceClient(ctrl *gomock.Controller) *MockCertificateAuthorityServiceClient {
	mock := &MockCertificateAuthorityServiceClient{ctrl: ctrl}
	mock.recorder = &MockCertificateAuthorityServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateAuthorityServiceClient) EXPECT() *MockCertificateAuthorityServiceClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCertificateAuthorityServiceClient) Create(ctx context.Context, in *certificate_authority.CreateRequest, opts ...grpc.CallOption) (*certificate_authority.CreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*certificate_authority.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCertificateAuthorityServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCertificateAuthorityServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockCertificateAuthorityServiceClient) Delete(ctx context.Context, in *certificate_authority.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCertificateAuthorityServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCertificateAuthorityServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockCertificateAuthorityServiceClient) Get(ctx context.Context, in *certificate_authority.GetRequest, opts ...grpc.CallOption) (*certificate_authority.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*certificate_authority.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCertificateAuthorityServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCertificateAuthorityServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockCertificateAuthorityServiceClient) List(ctx context.Context, in *certificate_authority.ListRequest, opts ...grpc.CallOption) (*certificate_authority.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*certificate_authority.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCertificateAuthorityServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCertificateAuthorityServiceClient)(nil).List), varargs...)
}

// Patch mocks base method.
func (m *MockCertificateAuthorityServiceClient) Patch(ctx context.Context, in *certificate_authority.PatchRequest, opts ...grpc.CallOption) (*certificate_authority.PatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*certificate_authority.PatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockCertificateAuthorityServiceClientMockRecorder) Patch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCertificateAuthorityServiceClient)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockCertificateAuthorityServiceClient) Update(ctx context.Context, in *certificate_authority.UpdateRequest, opts ...grpc.CallOption) (*certificate_authority.UpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*certificate_authority.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCertificateAuthorityServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCertificateAuthorityServiceClient)(nil).Update), varargs...)
}
