// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Apiserver apiserver
// swagger:model apiserver
type Apiserver struct {

	// ca
	// Min Length: 1
	Ca string `json:"ca,omitempty"`

	// cert
	// Min Length: 1
	Cert string `json:"cert,omitempty"`

	// description
	// Min Length: 1
	Description string `json:"description,omitempty"`

	// hostname
	// Min Length: 1
	Hostname string `json:"hostname,omitempty"`

	// key
	// Min Length: 1
	Key string `json:"key,omitempty"`
}

// Validate validates this apiserver
func (m *Apiserver) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCa(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCert(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Apiserver) validateCa(formats strfmt.Registry) error {

	if swag.IsZero(m.Ca) { // not required
		return nil
	}

	if err := validate.MinLength("ca", "body", string(m.Ca), 1); err != nil {
		return err
	}

	return nil
}

func (m *Apiserver) validateCert(formats strfmt.Registry) error {

	if swag.IsZero(m.Cert) { // not required
		return nil
	}

	if err := validate.MinLength("cert", "body", string(m.Cert), 1); err != nil {
		return err
	}

	return nil
}

func (m *Apiserver) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MinLength("description", "body", string(m.Description), 1); err != nil {
		return err
	}

	return nil
}

func (m *Apiserver) validateHostname(formats strfmt.Registry) error {

	if swag.IsZero(m.Hostname) { // not required
		return nil
	}

	if err := validate.MinLength("hostname", "body", string(m.Hostname), 1); err != nil {
		return err
	}

	return nil
}

func (m *Apiserver) validateKey(formats strfmt.Registry) error {

	if swag.IsZero(m.Key) { // not required
		return nil
	}

	if err := validate.MinLength("key", "body", string(m.Key), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Apiserver) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Apiserver) UnmarshalBinary(b []byte) error {
	var res Apiserver
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
